# Generated by Django 4.1.6 on 2023-03-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time_out',
            field=models.TimeField(auto_now=True),
        ),
    ]
